# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _image
else:
    import _image

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)



def clip(val, lo, hi):
    return _image.clip(val, lo, hi)
class pixel(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    len = property(_image.pixel_len_get, _image.pixel_len_set)
    alpha = property(_image.pixel_alpha_get, _image.pixel_alpha_set)
    _in = property(_image.pixel__in_get, _image.pixel__in_set)

    def __init__(self, *args):
        _image.pixel_swiginit(self, _image.new_pixel(*args))
    __swig_destroy__ = _image.delete_pixel

    def __add__(self, *args):
        return _image.pixel___add__(self, *args)

    def __sub__(self, *args):
        return _image.pixel___sub__(self, *args)

    def __mul__(self, *args):
        return _image.pixel___mul__(self, *args)

    def __truediv__(self, *args):
        return _image.pixel___truediv__(self, *args)
    __div__ = __truediv__



    def __xor__(self, scalar):
        return _image.pixel___xor__(self, scalar)

    def __and__(self, other):
        return _image.pixel___and__(self, other)

    def __or__(self, other):
        return _image.pixel___or__(self, other)

    def __lt__(self, other):
        return _image.pixel___lt__(self, other)

    def __gt__(self, other):
        return _image.pixel___gt__(self, other)

    def magnitude(self):
        return _image.pixel_magnitude(self)

# Register pixel in _image:
_image.pixel_swigregister(pixel)



